backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads" # Where uploaded images go in the repo
public_folder: "/images/uploads"

site_url: https://spy107portfolio.netlify.app

collections:
  - name: "projects"
    label: "Projects"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "GitHub Link", name: "github", widget: "string" }
      - { label: "Live Demo", name: "demo", widget: "string" }

  - name: "about"
    label: "About"
    files:
      - label: "About Page"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
